const ERRORS_CODE = {
    'DATA_SHOULD_BE_STRING': 'DATA SHOULD BE STRING',
    'DATA_SHOULD_BE_MORSE': 'DATA_SHOULD_BE_MORSE',
    'CHAR_DOESNT_EXIST': 'CHAR_DOESNT_EXIST',
};

export default ERRORS_CODE;