const ERRORS_CODE = {
    'DATA_SHOULD_BE_STRING': 'DATA SHOULD BE STRING',
    'DATA_SHOULD_BE_MORSE': 'DATA_SHOULD_BE_MORSE',
    'CHAR_DOESNT_EXIST': 'CHAR DOESNT EXIST',
    'MORSE_SIGN_ISNT_SUPPORTED': 'THIS MORSE CODE SIGN IS NOT SUPPORTED',
};

export default ERRORS_CODE;