const ERRORS_CODE = {
    'DATA_SHOULD_BE_STRING': 'DATA_SHOULD_BE_STRING',
    'DATA_SHOULD_BE_MORSE': 'DATA_SHOULD_BE_MORSE',
    'CHAR_DOESNT_EXIST': 'CHAR_DOESNT_EXIST',
    'MORSE_SIGN_ISNT_SUPPORTED': 'MORSE_SIGN_ISNT_SUPPORTED',
};

export default ERRORS_CODE;